### ISSUE TITLE
Functionality & Minor UI/UX Change

### ISSUE THREAD

**Issue by ChugilC** [Subhi-c/Advice-generator#1]
- When clicking the button, new quote is not generating
- Make a cursor pointer for the button element

**Comment by Subhi-c** [comment]
Button functionality was resolved .👍🏻

**Comment by Subhi-c** [comment]
> * When clicking the button, new quote is not generating
> * Make a cursor pointer for the button element

Resolved Button Functionality👍🏻

**Comment by ChugilC** [comment]
Still every time same quote is fetching 
![image](https://user-images.githubusercontent.com/62885534/234621391-a2470343-0ebe-4481-88fb-307ca56e34ac.png)

**Comment by Subhi-c** [comment]
@ChugilC  The quote-fetching functionality is working fine. Furthermore, closing this issue. Also, thanks for your genuine feedback
